//
//  CompanyUpdateInfosInteractor.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/26/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompanyUpdateInfosBusinessLogic
{
  func doSomething(request: CompanyUpdateInfos.Something.Request)
}

protocol CompanyUpdateInfosDataStore
{
  //var name: String { get set }
}

class CompanyUpdateInfosInteractor: CompanyUpdateInfosBusinessLogic, CompanyUpdateInfosDataStore
{
  var presenter: CompanyUpdateInfosPresentationLogic?
  var worker: CompanyUpdateInfosWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CompanyUpdateInfos.Something.Request)
  {
    worker = CompanyUpdateInfosWorker()
    worker?.doSomeWork()
    
    let response = CompanyUpdateInfos.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
