//
//  CompanyUpdateInfosRouter.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/26/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CompanyUpdateInfosRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CompanyUpdateInfosDataPassing
{
  var dataStore: CompanyUpdateInfosDataStore? { get }
}

class CompanyUpdateInfosRouter: NSObject, CompanyUpdateInfosRoutingLogic, CompanyUpdateInfosDataPassing
{
  weak var viewController: CompanyUpdateInfosViewController?
  var dataStore: CompanyUpdateInfosDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CompanyUpdateInfosViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CompanyUpdateInfosDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
