//
//  CompanyRegisterPresenter.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/19/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompanyRegisterPresentationLogic
{
  func presentSomething(response: CompanyRegister.Something.Response)
}

class CompanyRegisterPresenter: CompanyRegisterPresentationLogic
{
  weak var viewController: CompanyRegisterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CompanyRegister.Something.Response)
  {
    let viewModel = CompanyRegister.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
