//
//  CompanyRegisterWorker.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/19/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CompanyRegisterWorker
{
  func doSomeWork()
  {
  }
}
