//
//  CompanyRegisterInteractor.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/19/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompanyRegisterBusinessLogic
{
  func doSomething(request: CompanyRegister.Something.Request)
}

protocol CompanyRegisterDataStore
{
  //var name: String { get set }
}

class CompanyRegisterInteractor: CompanyRegisterBusinessLogic, CompanyRegisterDataStore
{
  var presenter: CompanyRegisterPresentationLogic?
  var worker: CompanyRegisterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CompanyRegister.Something.Request)
  {
    worker = CompanyRegisterWorker()
    worker?.doSomeWork()
    
    let response = CompanyRegister.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
