//
//  CompleteProfileStepOneInteractor.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/25/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompleteProfileStepOneBusinessLogic
{
    func updateAddress(country: String, state: String, city: String, street: String, postalCode: Int)
}

protocol CompleteProfileStepOneDataStore
{
    //var name: String { get set }
}

class CompleteProfileStepOneInteractor: CompleteProfileStepOneBusinessLogic, CompleteProfileStepOneDataStore
{
    func updateAddress(country: String, state: String, city: String, street: String, postalCode: Int) {
        worker = CompleteProfileStepOneWorker()
       
        worker?.updateAddress(country: country, state: state, city: city, street: street, postalCode: postalCode).then{ company in
            self.presenter?.updateAddress()
        }.catch{
            error in
            self.presenter?.presentError(error: error)
        }
    }
    
    var presenter: CompleteProfileStepOnePresentationLogic?
    var worker: CompleteProfileStepOneWorker?
    //var name: String = ""
}
