//
//  CompleteProfileStepOneWorker.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/25/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promises
class CompleteProfileStepOneWorker
{
    func updateAddress(country : String, state: String, city: String, street: String, postalCode: Int)->Promise<company>
  {
    return CompanyAPIClient.update(country: country, state: state, city: city, street: street, postalCode: postalCode)
  }
}
