//
//  CompleteProfileStepOnePresenter.swift
//  CompanyProject
//
//  Created by ons ben slimen on 6/25/20.
//  Copyright (c) 2020 Ons Ben Slimen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompleteProfileStepOnePresentationLogic
{
    func updateAddress()
    func presentError(error: Error)
}

class CompleteProfileStepOnePresenter: CompleteProfileStepOnePresentationLogic
{
    weak var viewController: CompleteProfileStepOneDisplayLogic?
    
    func updateAddress() {
        viewController?.updateAddress()
    }
    
    func presentError(error: Error) {
        viewController?.displayError(error: error)
    }
    
    
    
    
    
}
